name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: "Login to Docker Hub"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build the Docker image
        run: docker build . -t ${{ secrets.DOCKER_HUB_USERNAME }}/m3h1a --file Dockerfile --tag m3h1a:$(date +%s)
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/m3h1a
